#!/usr/bin/env python3
"""Rasterises docs/n8n-logo.svg (n8n mark, from homarr-labs/dashboard-icons) into A8 alpha masks for LVGL -> src/ui/logo_data.h.
The firmware tints them with n8n's brand colour at draw time.   python3 scripts/gen_logo.py   (needs inkscape + Pillow)"""
import subprocess, tempfile, os
from PIL import Image
SIZES = [28, 36, 44, 56, 72, 96, 128]   # widths in px; aspect is 512:269.6
root = os.path.join(os.path.dirname(__file__), "..")
svg = os.path.join(root, "docs", "n8n-logo.svg")
out = ['// generated by scripts/gen_logo.py - n8n logo as A8 masks', '#pragma once', '#include <lvgl.h>', 'namespace ui {']
for w in SIZES:
    h = round(w * 269.6 / 512.1)
    png = tempfile.mktemp(suffix=".png")
    subprocess.run(["inkscape", svg, "--export-type=png", f"--export-filename={png}", f"--export-width={w * 4}", "--export-background-opacity=0"],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    im = Image.open(png).convert("RGBA").resize((w, h), Image.LANCZOS)   # 4x supersampling -> clean edges
    a = bytes(im.getchannel("A").tobytes())
    os.remove(png)
    out.append(f'alignas(4) static const uint8_t logo{w}_map[{len(a)}] = {{' + ",".join(str(b) for b in a) + '};')
    out.append(f'static const lv_image_dsc_t logo{w} = {{{{LV_IMAGE_HEADER_MAGIC, LV_COLOR_FORMAT_A8, 0, {w}, {h}, {w}, 0}}, {len(a)}, logo{w}_map, nullptr, nullptr}};')
out.append('static const lv_image_dsc_t* const kLogos[] = {' + ", ".join(f"&logo{w}" for w in SIZES) + '};')
out.append('}  // namespace ui')
open(os.path.join(root, "src", "ui", "logo_data.h"), "w").write("\n".join(out) + "\n")
print("ok", SIZES)
