#!/usr/bin/env python3
"""docs/n8n-api-routes.txt -> src/core/routes_data.h (explorer table)."""
import re, sys
HINTS = {
 "POST /workflows": '{"name":"New workflow","nodes":[],"connections":{},"settings":{}}',
 "PUT /workflows/:workflowId": '{"name":"Renamed","nodes":[],"connections":{},"settings":{}}',
 "PUT /workflows/:workflowId/tags": '[{"id":"TAG_ID"}]',
 "PUT /workflows/:workflowId/transfer": '{"destinationProjectId":"PROJECT_ID"}',
 "POST /credentials": '{"name":"My credential","type":"httpHeaderAuth","data":{"name":"X-Key","value":"secret"}}',
 "PATCH /credentials/:credentialId": '{"name":"Renamed"}',
 "PUT /credentials/:credentialId/transfer": '{"destinationProjectId":"PROJECT_ID"}',
 "POST /tags": '{"name":"production"}',
 "PUT /tags/:tagId": '{"name":"renamed"}',
 "POST /variables": '{"key":"MY_VAR","value":"hello"}',
 "PUT /variables/:id": '{"key":"MY_VAR","value":"world"}',
 "POST /users": '[{"email":"new@example.com","role":"global:member"}]',
 "PATCH /users/:userId/role": '{"newRoleName":"global:member"}',
 "POST /projects": '{"name":"Team project"}',
 "PUT /projects/:projectId": '{"name":"Renamed project"}',
 "POST /projects/:projectId/users": '{"relations":[{"userId":"USER_ID","role":"project:editor"}]}',
 "PATCH /projects/:projectId/users/:userId": '{"role":"project:viewer"}',
 "POST /projects/:projectId/folders": '{"name":"Folder","parentFolderId":null}',
 "PATCH /projects/:projectId/folders/:folderId": '{"name":"Renamed folder"}',
 "POST /audit": '{"additionalOptions":{"categories":["credentials","database","nodes","filesystem","instance"],"daysAbandonedWorkflow":90}}',
 "POST /source-control/pull": '{"force":true}',
 "POST /source-control/push": '{"message":"Update from device","force":false}',
 "POST /executions/stop": '{"status":["running","waiting"]}',
 "POST /executions/:executionId/retry": '{"loadWorkflow":false}',
 "PUT /executions/:executionId/tags": '[{"id":"TAG_ID"}]',
 "POST /data-tables": '{"name":"my_table","columns":[{"name":"title","type":"string"}]}',
 "PATCH /data-tables/:dataTableId": '{"name":"renamed_table"}',
 "POST /data-tables/:dataTableId/columns": '{"name":"count","type":"number"}',
 "POST /data-tables/:dataTableId/rows": '{"data":[{"title":"hello"}],"returnType":"count"}',
 "POST /community-packages": '{"name":"n8n-nodes-example"}',
 "POST /roles": '{"displayName":"Custom role","roleType":"project","scopes":["workflow:read"]}',
 "POST /settings/log-streaming/destinations": '{"__type":"$$MessageEventBusDestinationWebhook","label":"hook","url":"https://example.com"}',
}
rows = []
for line in open("docs/n8n-api-routes.txt"):
    m = re.match(r"(GET|POST|PUT|PATCH|DELETE)\s+(\S+)", line)
    if not m: continue
    meth, path = m.groups()
    seg = path.strip("/").split("/")
    grp = seg[1] if seg[0] == "settings" and len(seg) > 1 else seg[0]
    hint = HINTS.get(f"{meth} {path}", "{}" if meth in ("POST", "PUT", "PATCH") else "")
    rows.append((grp, path, meth, hint))
rows.sort(key=lambda r: (r[0], r[1], ["GET","POST","PUT","PATCH","DELETE"].index(r[2])))
esc = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
with open("src/core/routes_data.h", "w") as f:
    f.write("// GENERATED by scripts/gen_routes.py from docs/n8n-api-routes.txt - do not edit\n#pragma once\n")
    f.write("struct Route { const char* method; const char* path; const char* group; const char* hint; };\n")
    f.write("static const Route kRoutes[] = {\n")
    for g, p, m, h in rows:
        f.write(f'  {{"{m}", "{p}", "{g}", "{esc(h)}"}},\n')
    f.write("};\nstatic const int kRouteCount = %d;\n" % len(rows))
print(len(rows), "routes")
